# Generated by Django 5.2.5 on 2025-08-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='disk_free_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='disk_total_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='disk_used_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='logical_cores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='physical_cores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='processor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ram_available_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ram_total_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ram_used_gb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
